# Generated by Django 5.2 on 2025-05-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_allergen_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergen',
            options={'verbose_name_plural': 'Allergens'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name_plural': 'Cart items'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name_plural': 'Menu items'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Order items'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name_plural': 'Restaurants'},
        ),
    ]
