# Generated by Django 5.2 on 2025-05-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_foodcategory_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(choices=[('savory', 'อาหารคาว'), ('dessert', 'ของหวาน'), ('grocery', 'ของชำ')], max_length=100),
        ),
    ]
